ALTER TYPE "KnowledgeCaptureItemKind" ADD VALUE IF NOT EXISTS 'RELATION';
ALTER TYPE "KnowledgeCaptureItemKind" ADD VALUE IF NOT EXISTS 'EVENT';
ALTER TYPE "KnowledgeCaptureItemKind" ADD VALUE IF NOT EXISTS 'DECISION';
